### ISSUE TITLE
google.py KeyError: 'id'

### ISSUE THREAD

**Issue by killermonkeys** [rckclmbr/pyportify#104] opened 2017-05-12 23:02 UTC
(1159/1260) Found 'Pavement - Silence Kit' in Google Music
(1156/1260) No match found for 'Bonnie "Prince" Billy - Today I Was An Evil One' in Google Music
(102/1260) Found 'Bob Dylan - Dirt Road Blues' in Google Music
(240/1260) Found 'Sonic Youth - Mildred Pierce' in Google Music
(378/1260) Found 'Jeff Buckley - Grace' in Google Music
(1160/1260) Found 'Pavement - Elevate Me Later' in Google Music
(241/1260) Found 'Sonic Youth - Cinderella's Big Score' in Google Music
(103/1260) Found 'Bob Dylan - Standing in the Doorway' in Google Music
(1161/1260) Found 'Pavement - Stop Breathin'' in Google Music
(242/1260) Found 'Sonic Youth - Scooter And Jinx' in Google Music
(1158/1260) No match found for 'Bonnie "Prince" Billy - Raining In Darling' in Google Music
(1157/1260) No match found for 'Bonnie "Prince" Billy - Black' in Google Music
(379/1260) Found 'Jeff Buckley - Last Goodbye' in Google Music
Creating in Google Music... Error handling request
Traceback (most recent call last):
  File "/Users/kstoltz/miniconda3/lib/python3.6/site-packages/aiohttp/server.py", line 265, in start
    yield from self.handle_request(message, payload)
  File "/Users/kstoltz/miniconda3/lib/python3.6/site-packages/aiohttp/web.py", line 96, in handle_request
    resp = yield from handler(request)
  File "/Users/kstoltz/miniconda3/lib/python3.6/site-packages/pyportify/middlwares.py", line 18, in index_handler
    ret = yield from handler(request)
  File "/Users/kstoltz/miniconda3/lib/python3.6/site-packages/pyportify/app.py", line 117, in transfer_start
    yield from transfer_playlists(request, s, g, lists)
  File "/Users/kstoltz/miniconda3/lib/python3.6/site-packages/pyportify/app.py", line 177, in transfer_playlists
    yield from g.add_songs_to_playlist(playlist_id, gm_track_ids)
  File "/Users/kstoltz/miniconda3/lib/python3.6/site-packages/pyportify/google.py", line 95, in add_songs_to_playlist
    added_ids = [e['id'] for e in res['mutate_response']]
  File "/Users/kstoltz/miniconda3/lib/python3.6/site-packages/pyportify/google.py", line 95, in <listcomp>
    added_ids = [e['id'] for e in res['mutate_response']]
KeyError: 'id'

Here is the playlist I was trying to import, it's public: https://open.spotify.com/user/lunsku/playlist/0OG0sShb7v1eU5brRfKDpv

**Comment by shan3k** [comment] 2017-05-14 22:38
Duplicate of #101 I believe.

**Comment by gabeorlanski** [comment] 2017-05-20 21:36
Getting this as well.

**Comment by rckclmbr** [comment] 2017-06-03 06:27
This should be fixed in v0.3.14, give it a try and let me know.

**Closed by rckclmbr** 2017-06-03 06:27 UTC
