### ISSUE TITLE
Trojan alert

### ISSUE THREAD

**Issue by KountryDad05** [rckclmbr/pyportify#147] opened 2018-09-24 06:24 UTC
SO I downloaded the exe and when trying it in Chrome, I got the message that the file was unsafe and would not let me open it. I then tried it in Internet Explorer and it downloaded. But once I ran it, I got a virus alert again.

Please look in to this.

**Comment by rckclmbr** [comment] 2018-09-24 22:08
Duplicate of #106, there's no actually a virus.  Was it actually Chrome that alerted you, or was it another piece of software?

**Closed by rckclmbr** 2018-09-24 22:08 UTC
