### ISSUE TITLE
Failed With AttributeError

### ISSUE THREAD

**Issue by Morabito** [rckclmbr/pyportify#40] opened 2015-10-22 21:09 UTC
Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
        result = self._run(*self.args, **self.kwargs)
      File "/usr/local/lib/python2.7/site-packages/pyportify/views.py", line 207, in search_gm_track
        track = g.find_best_track(search_query)
      File "/usr/local/lib/python2.7/site-packages/pyportify/google.py", line 64, in find_best_track
        data = self.search_all_access(search_query)
      File "/usr/local/lib/python2.7/site-packages/pyportify/google.py", line 60, in search_all_access
        data = self._http_get(url)
      File "/usr/local/lib/python2.7/site-packages/pyportify/google.py", line 90, in _http_get
        res = self._sj_client.get(SJ_URL + url, headers)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/client.py", line 184, in get
        return self.request(METHOD_GET, request_uri, headers=headers)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/client.py", line 172, in request
        block_size=self.block_size, method=method.upper(), headers_type=self.headers_type)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 286, in __init__
        super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 158, in __init__
        self._read_headers()
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 179, in _read_headers
        self.feed(data)
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 118, in _on_header_field
        self._flush_header()
      File "/usr/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 133, in _flush_header
        self._headers_index.add(self._current_header_field,
    AttributeError: 'dict' object has no attribute 'add'
    <Greenlet at 0x102a9c410: search_gm_track((880, u'spotify:user:ZZZZZZZZ:playlist:6bHsAJK)> failed with AttributeError

    127.0.0.1 - - [2015-10-22 17:01:44] "POST /portify/transfer/start HTTP/1.1" 200 165 42.383584

**Comment by rckclmbr** [comment] 2015-10-22 21:12
Duplicate of #38

**Closed by rckclmbr** 2015-10-22 21:12 UTC
