### ISSUE TITLE
Suggest to users to use "app passwords"

### ISSUE THREAD

**Issue by killermonkeys** [rckclmbr/pyportify#103] opened 2017-05-12 22:54 UTC
https://support.google.com/accounts/answer/185833

Google allows users to use "app passwords" these are alternative (randomly generated) passwords that are used for a single application. They offer some containment of the risk of typing in your password into a non-google owned app. 

You should suggest that users create an app password for use with pyportify, which they can later delete without having to share their existing password with your app. I've just used it this way and it works (thanks btw works great)

**Comment by rckclmbr** [comment] 2017-06-03 06:36
Duplicate of #61

This would be helpful, a lot of people are tripped up by this.

**Closed by rckclmbr** 2017-06-03 06:36 UTC
