### ISSUE TITLE
Seg Fault - Might be Linux related?

### ISSUE THREAD

**Issue by darthjoey91** [rckclmbr/pyportify#4] opened 2015-01-12 23:30 UTC
I keep getting a seg fault when I try to log into Google using an app password. I have not tried turning off two-factor.

I also get a seg-fault when just trying the copyall version of the command, before I can log in.

Running Linux Mint 17.1.

**Comment by rckclmbr** [comment] 2015-01-13 06:44
Possibly related to #3

**Comment by rckclmbr** [comment] 2015-01-18 06:26
Definitely duplicate of #3, I'll close this as the other has more information

**Closed by rckclmbr** 2015-01-18 06:26 UTC
